# Generated by Django 4.2.4 on 2023-08-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qualifications', models.CharField(max_length=50)),
                ('shift', models.CharField(max_length=20)),
            ],
        ),
    ]
