# Generated by Django 4.2.4 on 2023-08-31 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurse',
            old_name='id',
            new_name='Nurse_Id',
        ),
        migrations.RenameField(
            model_name='nurse',
            old_name='qualifications',
            new_name='Qualifications',
        ),
        migrations.RenameField(
            model_name='nurse',
            old_name='shift',
            new_name='Shift',
        ),
    ]
