# Generated by Django 4.2.4 on 2023-08-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('Doctor_ID', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('Doctor_name', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('Email', models.CharField(max_length=50)),
                ('Qualification', models.TextField()),
                ('Shift', models.CharField(max_length=15)),
                ('Phone', models.CharField(max_length=15)),
                ('Account_no', models.CharField(max_length=20)),
                ('Salary', models.IntegerField(max_length=5)),
            ],
        ),
    ]
