# Generated by Django 4.2.4 on 2023-08-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('Medicine_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Generic_name', models.CharField(max_length=50)),
                ('Company', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
                ('Miligram', models.IntegerField()),
                ('Available_quantity', models.IntegerField()),
            ],
        ),
    ]
