# Generated by Django 4.2.4 on 2023-08-31 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_checkupitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkupitem',
            old_name='bloodpressure',
            new_name='Blood_Pressure',
        ),
        migrations.RenameField(
            model_name='checkupitem',
            old_name='id',
            new_name='Checkup_Id',
        ),
        migrations.RenameField(
            model_name='checkupitem',
            old_name='heartrate',
            new_name='Heartrate',
        ),
        migrations.RenameField(
            model_name='checkupitem',
            old_name='sugar',
            new_name='Sugar',
        ),
    ]
