# Generated by Django 4.2.4 on 2023-08-31 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('residents', '0002_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberappoint',
            name='Nurse_ID',
        ),
        migrations.AlterField(
            model_name='memberappoint',
            name='Doctor_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
        migrations.CreateModel(
            name='Medicine_chart',
            fields=[
                ('Chart_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Advice', models.CharField(max_length=500)),
                ('Date', models.DateField()),
                ('Member_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.member')),
            ],
        ),
    ]
